services:
  - type: web
    name: fastflowpe-blog
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PRISMA_DATABASE_URL
        sync: false
      - key: PAYLOAD_SECRET
        sync: false
      - key: NEXT_PUBLIC_SERVER_URL
        sync: false
      - key: CRON_SECRET
        generateValue: true
      - key: PREVIEW_SECRET
        generateValue: true
      - key: S3_BUCKET
        sync: false
      - key: S3_ENDPOINT
        sync: false
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
